export const CHANGE_MODAL = 'CHANGE_MODAL'
export const RESET_MODAL = 'RESET_MODAL'
export const DISPLAY_ERROR = 'DISPLAY_ERROR'
export const CHANGE_IS_MOBILE = 'CHANGE_IS_MOBILE';
export const CHANGE_WIDTH_AND_HEIGHT = 'CHANGE_WIDTH_AND_HEIGHT';

// auth
export const RESET_AUTHED = 'RESET_AUTHED'

export const RECEIVE_AUTH = 'RECEIVE_AUTH'
export const RECEIVE_JOIN_BIN = 'RECEIVE_JOIN_BIN'
export const RECEIVE_JOIN_BIN_ERROR = 'RECEIVE_JOIN_BIN_ERROR'
export const RECEIVE_BIN_EXISTS = 'RECEIVE_BIN_EXISTS'
export const RECEIVE_POSTS = 'RECEIVE_POSTS'
export const RECEIVE_CREATE_POST = 'RECEIVE_NEW_POST'
export const RECEIVE_REACTIONS = 'RECEIVE_REACTIONS'
export const RECEIVE_TITLE = 'RECEIVE_TITLE'

export const REQUEST_AUTH = 'REQUEST_AUTH'
export const REQUEST_CREATE_POST = 'REQUEST_NEW_POST'
export const REQUEST_DELETE_POST = 'REQUEST_DELETE_POST'
export const REQUEST_POSTS = 'REQUEST_POSTS'
export const REQUEST_TITLE = 'REQUEST_TITLE'
export const REQUEST_EDIT_BIN_TITLE = 'REQUEST_EDIT_BIN_TITLE'
export const REQUEST_ADD_REACTION = 'REQUEST_ADD_REACTION'
export const REQUEST_DELETE_REACTION = 'REQUEST_DELETE_REACTION'
