export const CHANGE_MODAL = 'CHANGE_MODAL'
export const RESET_MODAL = 'RESET_MODAL'
export const DISPLAY_ERROR = 'DISPLAY_ERROR'
export const CHANGE_IS_MOBILE = 'CHANGE_IS_MOBILE';
export const CHANGE_WIDTH_AND_HEIGHT = 'CHANGE_WIDTH_AND_HEIGHT';

// auth
export const RESET_AUTHED = 'RESET_AUTHED'

export const RECEIVE_AUTH = 'RECEIVE_AUTH'
export const RECEIVE_BIN = 'RECEIVE_BIN'

export const RECEIVE_POSTS = 'RECEIVE_POSTS'
export const RECEIVE_CREATE_POST = 'RECEIVE_NEW_POST'
export const RECEIVE_REACTIONS = 'RECEIVE_REACTIONS'
export const RECEIVE_TITLE = 'RECEIVE_TITLE'

export const REQUEST_CREATE_POST = 'REQUEST_NEW_POST'
export const REQUEST_DELETE_POST = 'REQUEST_DELETE_POST'
export const REQUEST_POSTS = 'REQUEST_POSTS'
export const REQUEST_TITLE = 'REQUEST_TITLE'


// ???
export const REQUEST_CREATE_BIN = 'REQUEST_CREATE_BIN'
export const RECEIVE_CREATE_BIN = 'RECEIVE_CREATE_BIN'

export const REQUEST_TOGGLE_REACTION = 'REQUEST_TOGGLE_REACTION'
export const RECEIVE_TOGGLE_REACTION = 'RECEIVE_TOGGLE_REACTION'

